package com.core.mapper;

import java.util.List;
import java.util.Objects;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Component;

import com.core.dtos.common.AddressSnapshotDTO;
import com.core.dtos.common.MoneyDTO;
import com.core.dtos.common.PageResult;
import com.core.dtos.estimate.EstimateDTO;
import com.core.dtos.estimate.EstimateEntryDTO;
import com.core.dtos.estimate.EstimateListItem;
import com.core.dtos.estimate.PublicEstimateDTO;
import com.core.dtos.estimate.PublicEstimateEntryDTO;
import com.core.dtos.payment.PaymentDTO;
import com.core.models.Client;
import com.core.models.Estimate;
import com.core.models.EstimateEntry;
import com.core.models.ExtraCharge;
import com.core.models.MasterVehicle;
import com.core.models.Payment;
import com.core.models.embedded.AddressSnapshot;
import com.core.models.embedded.Money;
import com.core.models.embedded.PackageSnapshot;
import com.core.services.common.AuditActorService;
import com.core.util.EstimateUtil;

import lombok.RequiredArgsConstructor;

@Component
@RequiredArgsConstructor
public class EstimateAssembler {

	private final ClientAssembler clientAssembler;
	private final VehicleAssembler vehicleAssembler;
	private final AuditActorService auditActorService;

	/**
	 * Lightweight employee response used by estimate create and update
	 * operations.
	 *
	 * The complete employee GET response is generated by
	 * assembleEmployeeDetail(...).
	 */
	public EstimateDTO assemble(
			Estimate estimate) {

		return assembleEstimate(
				estimate,
				List.of(),
				false);
	}

	/**
	 * Complete employee-only estimate response.
	 *
	 * Includes requested vehicle details, payments, audit information and
	 * employee-only extra-charge information.
	 */
	public EstimateDTO assembleEmployeeDetail(
			Estimate estimate,
			List<Payment> payments) {

		return assembleEstimate(
				estimate,
				payments,
				true);
	}

	private EstimateDTO assembleEstimate(
			Estimate estimate,
			List<Payment> payments,
			boolean includeEmployeeDetails) {

		return new EstimateDTO(
				estimate.getId(),
				estimate.getEstimateId(),
				estimate.getOrgId(),
				estimate.getStatus(),
				estimate.getEstimateDate(),
				estimate.getValidTill(),

				estimate.getClient() == null
						? null
						: clientAssembler.assemble(
						estimate.getClient()),

				estimate.getClientBillingEntity() == null
						? null
						: clientAssembler.enrichBillingEntity(
						estimate.getClientBillingEntity()),

				toMoneyDTO(
						estimate.getSubtotal()),

				toMoneyDTO(
						estimate.getDiscount()),

				toMoneyDTO(
						estimate.getTaxableAmount()),

				estimate.getGstSnapshot(),

				toMoneyDTO(
						estimate.getEstimatedPayable()),

				toMoneyDTO(
						estimate.getAdvanceAmount()),

				estimate.getRemarks(),

				estimate.getEntries() == null
						? List.of()
						: estimate.getEntries()
						.stream()
						.filter(Objects::nonNull)
						.map(entry -> assembleEntry(
								entry,
								includeEmployeeDetails))
						.toList(),

				payments == null
						? List.of()
						: payments.stream()
						.filter(Objects::nonNull)
						.map(this::assemblePayment)
						.toList(),

				estimate.getSentAt(),
				estimate.getViewedAt(),
				estimate.getPaymentInitiatedAt(),
				estimate.getPaidAt(),
				estimate.getConvertedAt(),
				estimate.getConvertedBookingId(),

				estimate.getCreatedAt(),
				estimate.getUpdatedAt(),

				resolveActorName(
						estimate.getCreatedBy()),

				resolveActorName(
						estimate.getUpdatedBy()));
	}

	/**
	 * Complete client-facing estimate response.
	 *
	 * This method intentionally uses a dedicated public DTO instead of the
	 * employee DTO. It includes the commercial information required by the
	 * public estimate viewer while excluding internal organisation and audit
	 * details.
	 */
	public PublicEstimateDTO assemblePublic(
			Estimate estimate,
			Money payableNow) {

		Client client = estimate.getClient();

		String clientName =
				client != null
						&& client.getName() != null
						? client.getName()
						.getDisplayName()
						: null;

		return new PublicEstimateDTO(
				estimate.getEstimateId(),
				estimate.getStatus(),

				clientName,

				client == null
						? null
						: client.getPhone(),

				client == null
						? null
						: client.getEmail(),

				estimate.getEstimateDate(),
				estimate.getValidTill(),

				toMoneyDTO(
						estimate.getSubtotal()),

				toMoneyDTO(
						estimate.getDiscount()),

				toMoneyDTO(
						estimate.getTaxableAmount()),

				estimate.getGstSnapshot(),

				toMoneyDTO(
						estimate.getEstimatedPayable()),

				toMoneyDTO(
						estimate.getAdvanceAmount()),

				toMoneyDTO(
						payableNow),

				estimate.getRemarks(),

				estimate.getCreatedAt(),

				resolvePublicOwnerName(
						estimate.getCreatedBy()),

				estimate.getEntries() == null
						? List.of()
						: estimate.getEntries()
						.stream()
						.filter(Objects::nonNull)
						.map(this::assemblePublicEntry)
						.toList());
	}

	private PublicEstimateEntryDTO assemblePublicEntry(
			EstimateEntry entry) {

		return new PublicEstimateEntryDTO(
				entry.getId(),
				entry.getEstimateEntryId(),

				assemblePublicPackage(
						entry.getPack()),

				assemblePublicVehicle(
						entry.getRequestedVehicle()),

				entry.getReportingTime(),
				entry.getDropTime(),

				toAddressDTO(
						entry.getReportingLocation()),

				toAddressDTO(
						entry.getDropLocation()),

				entry.getRunningDays(),
				entry.getExtraChargebleDistance(),
				entry.getExtraChargebleTime(),

				Boolean.TRUE.equals(
						entry.getNightChargeble()),

				entry.getCharges() == null
						? List.of()
						: entry.getCharges()
						.stream()
						.filter(Objects::nonNull)
						.map(this::assemblePublicExtraCharge)
						.toList(),

				toMoneyDTO(
						EstimateUtil.calculateLineTotal(
								entry)));
	}

	private PublicEstimateEntryDTO.PackageDetails assemblePublicPackage(
			PackageSnapshot pack) {

		if (pack == null) {
			return null;
		}

		return new PublicEstimateEntryDTO.PackageDetails(
				pack.getPackageId(),
				pack.getScope(),
				pack.getDutyType(),
				pack.getTime(),
				pack.getDistance(),
				pack.getUnit(),

				toMoneyDTO(
						pack.getBaseFare()),

				toMoneyDTO(
						pack.getExtraPerKM()),

				toMoneyDTO(
						pack.getExtraPerHS()),

				toMoneyDTO(
						pack.getNightCharge()));
	}

	private PublicEstimateEntryDTO.VehicleDetails assemblePublicVehicle(
			MasterVehicle vehicle) {

		if (vehicle == null) {
			return null;
		}

		return new PublicEstimateEntryDTO.VehicleDetails(
				vehicle.getId(),
				vehicle.getName(),
				vehicle.getPic(),
				vehicle.getBrand(),
				vehicle.getCategory(),
				vehicle.getSeats(),
				vehicle.getDoors(),
				vehicle.getTransmissionType(),
				vehicle.getFuelSystem(),
				vehicle.getModelYear());
	}

	private PublicEstimateEntryDTO.ExtraChargeDetails assemblePublicExtraCharge(
			ExtraCharge charge) {

		return new PublicEstimateEntryDTO.ExtraChargeDetails(
				charge.getId(),
				charge.getDescription(),

				toMoneyDTO(
						charge.getAmount()));
	}

	public PageResult<EstimateListItem> assemble(
			Page<Estimate> page) {

		Page<EstimateListItem> mappedPage =
				page.map(
						EstimateListItem::from);

		Sort.Order firstOrder =
				page.getSort()
						.stream()
						.findFirst()
						.orElse(
								Sort.Order.desc(
										"createdAt"));

		return PageResult.from(
				mappedPage,
				firstOrder.getProperty(),
				firstOrder.getDirection());
	}

	/**
	 * Lightweight entry representation used by non-detail employee responses.
	 *
	 * Requested vehicle details, entry audit information and extra-charge
	 * images remain hidden.
	 */
	public EstimateEntryDTO assembleEntry(
			EstimateEntry entry) {

		return assembleEntry(
				entry,
				false);
	}

	private EstimateEntryDTO assembleEntry(
			EstimateEntry entry,
			boolean includeEmployeeDetails) {

		return new EstimateEntryDTO(
				entry.getId(),
				entry.getEstimateEntryId(),

				/*
				 * Frozen package information captured when the estimate entry
				 * was created.
				 */
				entry.getPack(),

				entry.getMasterVehicleId(),

				includeEmployeeDetails
						&& entry.getRequestedVehicle() != null
						? vehicleAssembler.assemble(
						entry.getRequestedVehicle())
						: null,

				entry.getReportingTime(),
				entry.getDropTime(),

				toAddressDTO(
						entry.getReportingLocation()),

				toAddressDTO(
						entry.getDropLocation()),

				entry.getRunningDays(),
				entry.getExtraChargebleDistance(),
				entry.getExtraChargebleTime(),

				Boolean.TRUE.equals(
						entry.getNightChargeble()),

				entry.getCharges() == null
						? List.of()
						: entry.getCharges()
						.stream()
						.filter(Objects::nonNull)
						.map(charge -> assembleExtraCharge(
								charge,
								includeEmployeeDetails))
						.toList(),

				toMoneyDTO(
						EstimateUtil.calculateLineTotal(
								entry)),

				includeEmployeeDetails
						? entry.getCreatedAt()
						: null,

				includeEmployeeDetails
						? entry.getUpdatedAt()
						: null,

				includeEmployeeDetails
						? resolveActorName(
						entry.getCreatedBy())
						: null,

				includeEmployeeDetails
						? resolveActorName(
						entry.getUpdatedBy())
						: null);
	}

	private EstimateEntryDTO.ExtraChargeDTO assembleExtraCharge(
			ExtraCharge charge,
			boolean includeEmployeeDetails) {

		return new EstimateEntryDTO.ExtraChargeDTO(
				charge.getId(),
				charge.getDescription(),

				toMoneyDTO(
						charge.getAmount()),

				includeEmployeeDetails
						? charge.getImage()
						: null);
	}

	private PaymentDTO assemblePayment(
			Payment payment) {

		return new PaymentDTO(
				payment.getId(),
				payment.getPaymentMode(),
				payment.getTransactionNumber(),
				payment.getTransactionDate(),

				toMoneyDTO(
						payment.getReceivedAmount()),

				toMoneyDTO(
						payment.getTds()),

				payment.getGateway(),
				payment.getGatewayOrderId(),
				payment.getGatewayPaymentId(),
				payment.getStatus(),
				payment.getRemarks(),

				payment.getCreatedAt(),
				payment.getUpdatedAt(),

				resolveActorName(
						payment.getCreatedBy()),

				resolveActorName(
						payment.getUpdatedBy()));
	}

	/**
	 * Resolve the estimate creator for the public estimate page.
	 *
	 * Public estimate viewing must not fail because a legacy employee or user
	 * account has been deleted.
	 */
	private String resolvePublicOwnerName(
			String userId) {

		if (userId == null
				|| userId.isBlank()
				|| "SYSTEM".equalsIgnoreCase(
				userId)) {

			return "Sales Team";
		}

		try {

			String actorName =
					resolveActorName(
							userId);

			return actorName == null
					|| actorName.isBlank()
					? "Sales Team"
					: actorName;

		} catch (RuntimeException exception) {

			return "Sales Team";
		}
	}

	private String resolveActorName(
			String userId) {

		return auditActorService
				.resolve(userId)
				.displayName();
	}

	private AddressSnapshotDTO toAddressDTO(
			AddressSnapshot address) {

		if (address == null) {
			return null;
		}

		return new AddressSnapshotDTO(
				address.getFormattedAddress(),
				address.getGooglePlaceId(),
				address.getLatitude(),
				address.getLongitude());
	}

	private MoneyDTO toMoneyDTO(
			Money money) {

		if (money == null) {
			return null;
		}

		return new MoneyDTO(
				money.getAmount(),
				money.getCurrency());
	}
}