package com.core.models.enums;

public enum Authority {
	ORG_VIEW,
	ORG_EDIT,

	CLIENT_VIEW,
	CLIENT_ADD,
	CLIENT_EDIT,

	DRIVER_VIEW,
	DRIVER_ADD,
	DRIVER_EDIT,
	DRIVER_DELETE,

	BOOKING_VIEW,
	BOOKING_ADD,
	BOOKING_EDIT,
	BOOKING_CONFIRM,
	BOOKING_CANCEL,
	BOOKING_COMPLETE,
	BOOKING_ADD_DUTY,
	BOOKING_EDIT_DUTY,
	BOOKING_ALLOT_DUTY,
	BOOKING_REALLOT_DUTY,
	BOOKING_CLOSE_DUTY,
	BOOKING_RECLOSE_DUTY,
	BOOKING_ADD_PAYMENT,
	BOOKING_EDIT_PAYMENT,
	BOOKING_CONFIRM_PAYMENT,

	INVOICE_GENERATE,
	INVOICE_REGENERATE,

	PURCHASE_INVOICE_VIEW,
	PURCHASE_INVOICE_ADD,
	PURCHASE_INVOICE_EDIT,
	PURCHASE_INVOICE_COMPLETE,
	PURCHASE_INVOICE_CANCEL,

	PAYMENT_OUT_VIEW,
	PAYMENT_OUT_ADD,
	PAYMENT_OUT_EDIT,
	PAYMENT_OUT_CANCEL,

	PACKAGE_VIEW,
	PACKAGE_ADD,
	PACKAGE_EDIT,
	PACKAGE_DELETE,

	EMPLOYEE_VIEW,
	EMPLOYEE_ADD,
	EMPLOYEE_EDIT,
	EMPLOYEE_RESET_PASSWORD,
	EMPLOYEE_UPDATE_AUTHORITIES,

	FINANCIAL_YEAR_VIEW,
	FINANCIAL_YEAR_ADD,
	FINANCIAL_YEAR_EDIT,

	ORG_BILLING_ENTITY_VIEW,
	ORG_BILLING_ENTITY_ADD,
	ORG_BILLING_ENTITY_EDIT,

	FLEET_VEHICLE_VIEW,
	FLEET_VEHICLE_ADD,
	FLEET_VEHICLE_EDIT,
	FLEET_VEHICLE_DELETE,

	MASTER_VEHICLE_VIEW,
	MASTER_VEHICLE_ADD,
	MASTER_VEHICLE_EDIT,
	MASTER_VEHICLE_DELETE,

	GARAGE_ADD,
	GARAGE_EDIT,
	GARAGE_VIEW,

	ORG_NOTIFICATION_CONFIG_VIEW,
	ORG_NOTIFICATION_CONFIG_EDIT,

	ORG_PAYMENT_GATEWAY_CONFIG_VIEW,
	ORG_PAYMENT_GATEWAY_CONFIG_EDIT,

	DATA_EXCHANGE_VIEW,
	DATA_EXCHANGE_EXPORT,
	DATA_EXCHANGE_IMPORT,

	REPORT_VIEW,
	REPORT_REQUEST,
	REPORT_DOWNLOAD,
	REPORT_DELETE,
}