package com.core.models.enums;

public enum ReportType {
    GSTR1,
    GSTR3B_SUMMARY,
    SALES_GST_REGISTER,
    PURCHASE_GST_REGISTER,
    HSN_SUMMARY,
    B2B_REGISTER,
    B2C_REGISTER,

    SALES_REGISTER,
    PURCHASE_REGISTER,
    SALES_SUMMARY,
    PURCHASE_SUMMARY,
    OUTSTANDING_RECEIVABLES,
    OUTSTANDING_PAYABLES,

    CLIENT_STATEMENT,
    VENDOR_STATEMENT,
    CLIENT_LEDGER,
    CLIENT_BILLING_ENTITY_LEDGER,
    VENDOR_LEDGER
}
